---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: les-gorgones
  labels:
    app.kubernetes.io/name: proxy
spec:
  volumes:
    - name: db-persistent-storage
      persistentVolumeClaim:
        claimName: db-pvc
  containers:
    - name: les-gorgones-database
      image: paulinemdt/microservice-database-image
      volumeMounts:
        - name: db-persistent-storage
          mountPath: /var/lib/mysql
    - name: les-gorgones-laravel-api
      image: paulinemdt/microservice-laravel-image
      env:
        - name: APP_KEY
          value: base64:E1W+tYjII5boogDNUejhNV68XRBy+s4pVCIANYryLBo=
      ports:
        - containerPort: 80
          name: http-web-api
    - name: les-gorgones-react-app
      image: paulinemdt/microservice-react-image
      ports:
        - containerPort: 3000
          name: http-web-app

---
apiVersion: v1
kind: Service
metadata:
  name: les-gorgones-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - name: les-gorgones-laravel-api
      protocol: TCP
      port: 80
      targetPort: http-web-api
    - name: les-gorgones-react-app
      protocol: TCP
      port: 3000
      targetPort: http-web-app
