---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: les-gorgones-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: les-gorgones-deployment
  labels:
    app.kubernetes.io/name: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: les-gorgones
  template:
    metadata:
      labels:
        app: les-gorgones
    spec:
    volumes:
      - name: db-persistent-storage
        persistentVolumeClaim:
          claimName: les-gorgones-db-pvc
    containers:
      - name: les-gorgones-database
        image: paulinemdt/microservice-database-image
        volumeMounts:
          - name: db-persistent-storage
            mountPath: /var/lib/mysql
      - name: les-gorgones-laravel-api
        image: paulinemdt/microservice-laravel-image
        ports:
          - containerPort: 80
            name: http-web-api
      - name: les-gorgones-react-app
        image: paulinemdt/microservice-react-image
        ports:
          - containerPort: 3000
            name: http-web-app

---
apiVersion: v1
kind: Service
metadata:
  name: les-gorgones-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - name: les-gorgones-laravel-api
      protocol: TCP
      port: 80
      targetPort: http-web-api
    - name: les-gorgones-react-app
      protocol: TCP
      port: 3000
      targetPort: http-web-app
