---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pm-lg-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-lg-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pm-lg
  template:
    metadata:
      labels:
          app: pm-lg
    spec:
      volumes:
        - name: pm-lg-db-persistent-storage
          persistentVolumeClaim:
            claimName: pm-lg-db-pvc
      containers:
        - name: database
          image: paulinemdt/microservice-database-image
          imagePullPolicy: Always
          volumeMounts:
            - name: pm-lg-db-persistent-storage
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: pm-lg-web-db

---
apiVersion: v1
kind: Service
metadata:
  name: pm-lg-database-service
spec:
  type: ClusterIP
  selector:
    app: pm-lg
  ports:
    - name: pm-lg-database-port
      protocol: TCP
      port: 3306
      targetPort: pm-lg-web-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-lg-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pm-lg
  template:
    metadata:
      labels:
        app: pm-lg
    spec:
      containers:
      - name: pm-lg-laravel-api-container
        image: paulinemdt/microservice-laravel-image
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            value: pm-lg-database-service
        ports:
          - containerPort: 80
            name: pm-lg-web-api

---
apiVersion: v1
kind: Service
metadata:
  name: pm-lg-backend-service
spec:
  type: LoadBalancer
  selector:
    app: pm-lg
  ports:
    - name: pm-lg-laravel-api-port
      protocol: TCP
      port: 80
      targetPort: pm-lg-web-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-lg-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pm-lg
  template:
    metadata:
      labels:
          app: pm-lg
    spec:
      containers:
      - name: pm-lg-react-app-container
        image: paulinemdt/microservice-react-image
        imagePullPolicy: Always
        env:
          - name: REACT_APP_API_URL
            value: http://4.225.73.105:80/
        ports:
          - containerPort: 3000
            name: pm-lg-web-app

---
apiVersion: v1
kind: Service
metadata:
  name: pm-lg-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: pm-lg
  ports:
    - name: pm-lg-react-app-port
      protocol: TCP
      port: 3000
      targetPort: pm-lg-web-app