---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pm-les-gorgones-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: pm-les-gorgones-pod
#  labels:
#    app: pm-les-gorgones
#spec:
#  volumes:
#    - name: db-persistent-storage
#      persistentVolumeClaim:
#        claimName: db-pvc
#  containers:
#    - name: database
#      image: paulinemdt/microservice-database-image
#      volumeMounts:
#        - name: db-persistent-storage
#          mountPath: /var/lib/mysql
#    - name: laravel-api
#      image: paulinemdt/microservice-laravel-image
#      env:
#        - name: APP_KEY
#          value: base64:E1W+tYjII5boogDNUejhNV68XRBy+s4pVCIANYryLBo=
#      ports:
#        - containerPort: 80
#          name: http-web-api
#    - name: react-app
#      image: paulinemdt/microservice-react-image
#      ports:
#        - containerPort: 3000
#          name: http-web-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-les-gorgones-database
spec:
  replicas: 1
  selector:
      matchLabels:
      app: pm-les-gorgones
  template:
    metadata:
    labels:
        app: pm-les-gorgones
    spec:
      volumes:
        - name: pm-les-gorgones-db-persistent-storage
          persistentVolumeClaim:
            claimName: pm-les-gorgones-db-pvc
      containers:
        - name: database
          image: paulinemdt/microservice-database-image
          volumeMounts:
            - name: pm-les-gorgones-db-persistent-storage
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: pm-les-gorgones-http-web-db

---
apiVersion: v1
kind: Service
metadata:
  name: pm-les-gorgones-database-service
spec:
  type: ClusterIP
  selector:
    app: pm-les-gorgones
  ports:
    - name: pm-les-gorgones-database-port
      protocol: TCP
      port: 3306
      targetPort: pm-les-gorgones-http-web-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-les-gorgones-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pm-les-gorgones
  template:
    metadata:
      labels:
        app: pm-les-gorgones
    spec:
      containers:
      - name: pm-les-gorgones-laravel-api-container
        image: paulinemdt/microservice-laravel-image
        env:
          - name: DB_HOST
            value: pm-les-gorgones-database-service
        ports:
          - containerPort: 80
            name: pm-les-gorgones-http-web-api

---
apiVersion: v1
kind: Service
metadata:
  name: pm-les-gorgones-backend-service
spec:
  type: LoadBalancer
  selector:
    app: pm-les-gorgones
  ports:
    - name: pm-les-gorgones-laravel-api-port
      protocol: TCP
      port: 80
      targetPort: pm-les-gorgones-http-web-api
